[2025-08-25T04:07:23.738+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T04:07:23.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [queued]>
[2025-08-25T04:07:23.759+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [queued]>
[2025-08-25T04:07:23.759+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-25T04:07:23.764+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_build> on 2025-08-25 04:02:12.834844+00:00
[2025-08-25T04:07:23.768+0000] {standard_task_runner.py:64} INFO - Started process 347 to run task
[2025-08-25T04:07:23.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'books_pipeline_dag', 'dbt_build', 'manual__2025-08-25T04:02:12.834844+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/books_pipeline_dag.py', '--cfg-path', '/tmp/tmpbkk4vpfa']
[2025-08-25T04:07:23.772+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask dbt_build
[2025-08-25T04:07:23.806+0000] {task_command.py:426} INFO - Running <TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [running]> on host 267439edb455
[2025-08-25T04:07:23.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='books_pipeline_dag' AIRFLOW_CTX_TASK_ID='dbt_build' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T04:02:12.834844+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-25T04:02:12.834844+00:00'
[2025-08-25T04:07:23.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T04:07:23.856+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-25T04:07:23.856+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt deps && dbt build --profiles-dir .']
[2025-08-25T04:07:23.865+0000] {subprocess.py:86} INFO - Output:
[2025-08-25T04:07:25.047+0000] {subprocess.py:93} INFO - [0m04:07:25  Running with dbt=1.10.9
[2025-08-25T04:07:25.113+0000] {subprocess.py:93} INFO - [0m04:07:25  Warning: No packages were found in packages.yml
[2025-08-25T04:07:25.114+0000] {subprocess.py:93} INFO - [0m04:07:25  Warning: No packages were found in packages.yml
[2025-08-25T04:07:28.122+0000] {subprocess.py:93} INFO - [0m04:07:28  Running with dbt=1.10.9
[2025-08-25T04:07:28.293+0000] {subprocess.py:93} INFO - [0m04:07:28  Registered adapter: duckdb=1.9.4
[2025-08-25T04:07:28.465+0000] {subprocess.py:93} INFO - [0m04:07:28  Found 2 models, 4 data tests, 429 macros
[2025-08-25T04:07:28.468+0000] {subprocess.py:93} INFO - [0m04:07:28
[2025-08-25T04:07:28.468+0000] {subprocess.py:93} INFO - [0m04:07:28  Concurrency: 4 threads (target='dev')
[2025-08-25T04:07:28.469+0000] {subprocess.py:93} INFO - [0m04:07:28
[2025-08-25T04:07:28.544+0000] {subprocess.py:93} INFO - [0m04:07:28
[2025-08-25T04:07:28.544+0000] {subprocess.py:93} INFO - [0m04:07:28  Finished running  in 0 hours 0 minutes and 0.07 seconds (0.07s).
[2025-08-25T04:07:28.545+0000] {subprocess.py:93} INFO - [0m04:07:28  Encountered an error:
[2025-08-25T04:07:28.545+0000] {subprocess.py:93} INFO - Runtime Error
[2025-08-25T04:07:28.545+0000] {subprocess.py:93} INFO -   IO Error: Could not set lock on file "/opt/***/data/warehouse/books.duckdb": Conflicting lock is held in PID 0. See also https://duckdb.org/docs/stable/connect/concurrency
[2025-08-25T04:07:29.569+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-25T04:07:29.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T04:07:29.589+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-25T04:07:29.593+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=books_pipeline_dag, task_id=dbt_build, run_id=manual__2025-08-25T04:02:12.834844+00:00, execution_date=20250825T040212, start_date=20250825T040723, end_date=20250825T040729
[2025-08-25T04:07:29.604+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task dbt_build (Bash command failed. The command returned a non-zero exit code 2.; 347)
[2025-08-25T04:07:29.620+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T04:07:29.631+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T04:07:29.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
