[2025-08-25T04:02:17.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T04:02:17.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [queued]>
[2025-08-25T04:02:17.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [queued]>
[2025-08-25T04:02:17.189+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-25T04:02:17.194+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_build> on 2025-08-25 04:02:12.834844+00:00
[2025-08-25T04:02:17.202+0000] {standard_task_runner.py:64} INFO - Started process 251 to run task
[2025-08-25T04:02:17.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'books_pipeline_dag', 'dbt_build', 'manual__2025-08-25T04:02:12.834844+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/books_pipeline_dag.py', '--cfg-path', '/tmp/tmpejibwcdd']
[2025-08-25T04:02:17.206+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask dbt_build
[2025-08-25T04:02:17.246+0000] {task_command.py:426} INFO - Running <TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T04:02:12.834844+00:00 [running]> on host 267439edb455
[2025-08-25T04:02:17.283+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='books_pipeline_dag' AIRFLOW_CTX_TASK_ID='dbt_build' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T04:02:12.834844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-25T04:02:12.834844+00:00'
[2025-08-25T04:02:17.284+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T04:02:17.290+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-25T04:02:17.290+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt deps && dbt build --profiles-dir .']
[2025-08-25T04:02:17.299+0000] {subprocess.py:86} INFO - Output:
[2025-08-25T04:02:18.525+0000] {subprocess.py:93} INFO - [0m04:02:18  Running with dbt=1.10.9
[2025-08-25T04:02:18.638+0000] {subprocess.py:93} INFO - [0m04:02:18  Warning: No packages were found in packages.yml
[2025-08-25T04:02:18.639+0000] {subprocess.py:93} INFO - [0m04:02:18  Warning: No packages were found in packages.yml
[2025-08-25T04:02:20.879+0000] {subprocess.py:93} INFO - [0m04:02:20  Running with dbt=1.10.9
[2025-08-25T04:02:21.010+0000] {subprocess.py:93} INFO - [0m04:02:21  Registered adapter: duckdb=1.9.4
[2025-08-25T04:02:21.170+0000] {subprocess.py:93} INFO - [0m04:02:21  Found 2 models, 4 data tests, 429 macros
[2025-08-25T04:02:21.172+0000] {subprocess.py:93} INFO - [0m04:02:21
[2025-08-25T04:02:21.172+0000] {subprocess.py:93} INFO - [0m04:02:21  Concurrency: 4 threads (target='dev')
[2025-08-25T04:02:21.172+0000] {subprocess.py:93} INFO - [0m04:02:21
[2025-08-25T04:02:21.230+0000] {subprocess.py:93} INFO - [0m04:02:21
[2025-08-25T04:02:21.231+0000] {subprocess.py:93} INFO - [0m04:02:21  Finished running  in 0 hours 0 minutes and 0.06 seconds (0.06s).
[2025-08-25T04:02:21.231+0000] {subprocess.py:93} INFO - [0m04:02:21  Encountered an error:
[2025-08-25T04:02:21.231+0000] {subprocess.py:93} INFO - Runtime Error
[2025-08-25T04:02:21.231+0000] {subprocess.py:93} INFO -   IO Error: Cannot open file "/opt/***/data/warehouse/books.duckdb": No such file or directory
[2025-08-25T04:02:22.238+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-25T04:02:22.241+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T04:02:22.255+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-25T04:02:22.262+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=books_pipeline_dag, task_id=dbt_build, run_id=manual__2025-08-25T04:02:12.834844+00:00, execution_date=20250825T040212, start_date=20250825T040217, end_date=20250825T040222
[2025-08-25T04:02:22.271+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task dbt_build (Bash command failed. The command returned a non-zero exit code 2.; 251)
[2025-08-25T04:02:22.282+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T04:02:22.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T04:02:22.293+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
